require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - "Gemfile"
    - "bin/**/*"
    - "db/**/*"
    - "log/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "config/**/*"

Style/Documentation:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Metrics:
  Enabled: false