require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - "Gemfile"
    - "bin/**/*"
    - "db/**/*"
    - "log/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "config/environments/*"
    - "config/puma.rb"